name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PUPPETEER_EXECUTABLE_PATH: /usr/bin/google-chrome
      PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: "true"
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: sudo apt-get update && sudo apt-get install -y google-chrome-stable
      - run: pnpm install --frozen-lockfile --no-audit --no-fund
      - run: pnpm lint
      - run: pnpm test
      - run: pnpm run build
      - uses: actions/upload-artifact@v3
        with:
          name: extension
          path: genai-scrubber.zip
